
SET IDENTITY_INSERT [dbo].[ModelType] ON 

GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (1, N'SMN230', 1, N'TCP/IP based 2 Door / 2 Reader Channel Access Controller + Battery back-up Power Supply & Metal Enclosure with Advance Security Features. It is compatible with smartENGINE - Advance Software (SSE Series).', 2, 2, 0, N'TCP,UDP', 1, 10000, 30000, N'No', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (2, N'SMN430', 2, N'TCP/IP based 4 Door /4 Reader Channel Access Controller + Battery back-up Power Supply & Metal Enclosure with Advance Security Features. It is compatible with smartENGINE - Advance Software (SSE Series).', 4, 4, 0, N'TCP,UDP', 1, 10000, 30000, N'No', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (3, N'SBN130 - P', 12, N'TCP/IP based Fingerprint based controller  + 16 X 2 LCD Display + Keypad with inbuilt Proximity Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 1, N'TCP,UDP', 1, 10000, 30000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (4, N'SBN130 - S', 12, N'TCP/IP based Fingerprint based controller  + 16 X 2 LCD Display + Keypad with inbuilt Mifare Smart Card Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series). Reads 26,32 bit Wiegand.', 1, 2, 1, N'TCP,UDP', 1, 10000, 30000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (5, N'SBN130 - HP', 12, N'TCP/IP based Fingerprint based controller  + 16 X 2 LCD Display + Keypad with inbuilt HID Prox Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 1, N'TCP,UDP', 1, 10000, 30000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (6, N'SBN130 - HI', 12, N'TCP/IP based Fingerprint based controller + 16 X 2 LCD Display + Keypad with inbuilt HID IClass Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 1, N'TCP,UDP', 1, 10000, 30000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (7, N'SBN930 - P', 12, N'TCP/IP based Fingerprint based controller  + 16 X 2 LCD Display + Keypad with inbuilt Proximity Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 1, N'TCP,UDP', 1, 10000, 30000, N'9500', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (8, N'SBN930 - S', 12, N'TCP/IP based Fingerprint based controller  + 16 X 2 LCD Display + Keypad with inbuilt Mifare Smart Card Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series). Reads 26,32 bit Wiegand.', 1, 2, 1, N'TCP,UDP', 1, 10000, 30000, N'9500', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (9, N'SBN930 - HP', 12, N'TCP/IP based Fingerprint based controller + Keypad + 16 X 2 LCD Display with inbuilt HID Prox Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 1, N'TCP,UDP', 1, 10000, 30000, N'9500', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (10, N'SBN930 - HI', 12, N'TCP/IP based Fingerprint based controller  + 16 X 2 LCD Display + Keypad with inbuilt HID IClass Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 1, N'TCP,UDP', 1, 10000, 30000, N'9500', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (11, N'SBL30 - AC', 4, N'TCP/IP based Fingerprint based Single door controller  + 16 X 2 LCD Display + Keypad with  Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 1, N'TCP,UDP', 1, 500, 50000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (12, N'SBL30 - AC -P', 4, N'TCP/IP based Fingerprint based Single door controller  + 16 X 2 LCD Display + Keypad with inbuilt embedded EM Proximity Reader  with Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 1, N'TCP,UDP', 1, 500, 50000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (13, N'SBL30 - AC -S', 4, N'TCP/IP based Fingerprint based Single door controller  + 16 X 2 LCD Display + Keypad with inbuilt embedded Mifare Smart Card Reader  with Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 1, N'TCP,UDP', 1, 500, 50000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (14, N'SBL30 - AC -HI', 4, N'TCP/IP based Fingerprint based Single door controller  + 16 X 2 LCD Display + Keypad with inbuilt embedded HID iClass Reader  with Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 1, N'TCP,UDP', 1, 500, 50000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (15, N'SBL30 - AC -HP', 4, N'TCP/IP based Fingerprint based Single door controller  + 16 X 2 LCD Display + Keypad with inbuilt embedded HID Prox Reader  with Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 1, N'TCP,UDP', 1, 500, 50000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (16, N'SBL30 - TA', 4, N'TCP/IP based Fingerprint based Time & Attandence Device  + 16 X 2 LCD Display + Keypad with  Power Supply. It is compatible with smartSOFT Lite/Enterprize Series.', 1, 2, 1, N'TCP,UDP', 1, 500, 50000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (17, N'SBL30 - TA - P', 4, N'TCP/IP based Fingerprint based Time & Attandence Device  + 16 X 2 LCD Display + Keypad with inbuilt embedded EM Proximity Reader  with Power Supply. It is compatible with smartSOFT Lite/Enterprize Series.', 1, 2, 1, N'TCP,UDP', 1, 500, 50000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (18, N'SBL30 - TA - S', 4, N'TCP/IP based Fingerprint based Time & Attandence Device  + 16 X 2 LCD Display + Keypad with inbuilt embedded Mifare Smart Card Reader with Power Supply. It is compatible with smartSOFT Lite/Enterprize Series.', 1, 2, 1, N'TCP,UDP', 1, 500, 50000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (19, N'SBL30 - TA - HI', 4, N'TCP/IP based Fingerprint based Time & Attandence Device  + 16 X 2 LCD Display + Keypad with inbuilt embedded HID iClass Reader   with Power Supply. It is compatible with smartSOFT Lite/Enterprize Series.', 1, 2, 1, N'TCP,UDP', 1, 500, 50000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (20, N'SBL30 - TA - HP', 4, N'TCP/IP based Fingerprint based Time & Attandence Device  + 16 X 2 LCD Display + Keypad with inbuilt embedded HID Prox Reader  with Power Supply. It is compatible with smartSOFT Lite/Enterprize Series.', 1, 2, 1, N'TCP,UDP', 1, 500, 50000, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (21, N'STN930 -P', 11, N'TCP/IP based Standalone controller + 16 X 2 LCD Display + Keypad  with inbuilt Proximity Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 0, N'TCP,UDP', 1, 10000, 30000, N'No', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (22, N'STN930 - S', 11, N'TCP/IP based Standalone controller  + 16 X 2 LCD Display + Keypad with inbuilt Smart Card Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series). Reads 26,32 bit Wiegand.', 1, 2, 0, N'TCP,UDP', 1, 10000, 30000, N'No', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (23, N'STN930 -HP', 11, N'TCP/IP based Standalone controller  + 16 X 2 LCD Display + Keypad with inbuilt HID Prox Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 0, N'TCP,UDP', 1, 10000, 30000, N'No', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (24, N'STN930 -HI', 11, N'TCP/IP based Standalone controller  + 16 X 2 LCD Display + Keypad with inbuilt HID IClass Reader embedded with Advance Security Features & Power Supply. It is compatible with smartENGINE - Advance Software (SSE Series).', 1, 2, 0, N'TCP,UDP', 1, 10000, 30000, N'No', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (25, N'SML430', 10, N'', 2, 4, 0, N'TCP,UDP', 0, 1000, 9999, N'No', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (26, N'SML830', 3, N'', 4, 8, 0, N'TCP,UDP', 0, 1000, 9999, N'No', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (27, N'SBNG30', 13, N'TCP/IP based Fingerprint based Standalone controller with one the best finger print sensor with User Capacity - 75,000,Template - 1900 (1:N), 3,00,000 (1:1) with Card Reader module, Transaction - 2,50,000    3.5'' TFT graphical Color Display LCD with Icons CapacitiveTouch Sense Keypad  Standard 12 V Power Supply      Modular Reader Provision* (EM Proximity/Mifare/HID I Class/HID Prox) *(Not Included)   Wiegand In & Wiegand Out Interface', 1, 2, 1, N'TCP,UDP', 1, 75000, 250000, N'1M-1910,4M-9590', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (28, N'SBNG30 - POE', 13, N'TCP/IP based Fingerprint based Standalone controller with one the best finger print sensor with User Capacity - 75,000, Template - 1900 (1:N), 3,00,000 (1:1) with Card Reader module, Transaction - 2,50,000 , 3.5'' TFT graphical Color Display LCD with Icons , CapacitiveTouch Sense Keypad , POE (Power on Ethernet) Power Supply , Modular Reader Provision* (EM Proximity/Mifare/HID I Class/HID Prox) *(Not Included), Wiegand In & Wiegand Out Interface', 1, 2, 1, N'TCP,UDP', 1, 75000, 250000, N'1M-1910,4M-9590', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (29, N'SBNG30 - Wifi', 13, N'Wifi based Fingerprint based Standalone controller with one the best finger print sensor with User Capacity - 75,000, Template - 1900 (1:N), 3,00,000 (1:1) with Card Reader module, Transaction - 2,50,000, 3.5'' TFT graphical Color Display LCD with Icons , CapacitiveTouch Sense Keypad Standard 12 V Power Supply Modular Reader Provision* (EM Proximity/Mifare/HID I Class/HID Prox) *(Not Included), Wiegand In & Wiegand Out Interface', 1, 2, 1, N'', 1, 75000, 250000, N'1M-1910,4M-9590', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (30, N'SBNG30 - GPRS', 13, N'GPRS based Fingerprint based Standalone controller with one the best finger print sensor with User Capacity - 75,000, Template - 1900 (1:N), 3,00,000 (1:1) with Card Reader module, Transaction - 2,50,000, 3.5'' TFT graphical Color Display LCD with Icons  , CapacitiveTouch Sense Keypad ,  Standard 12 V Power Supply Modular Reader Provision* (EM Proximity/Mifare/HID I Class/HID Prox) *(Not Included), Wiegand In & Wiegand Out Interface GPRS Enabled SIM Card in Customer Scope', 1, 2, 1, N'TCP,UDP,GPRS', 1, 75000, 250000, N'1M-1910,4M-9590', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (31, N'STNG30', 14, N'TCP/IP based  Standalone controller with User Capacity - 75,000 with Card reader module, Transaction - 2,50,000   ,  3.5'' TFT graphical Color Display LCD with Icons   , CapacitiveTouch Sense Keypad Standard 12 V Power Supply Modular Reader Provision* (EM Proximity/Mifare/HID I Class/HID Prox) *(Not Included), Wiegand In & Wiegand Out Interface', 1, 2, 0, N'TCP,UDP', 1, 75000, 250000, N'', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (32, N'STNG30 - POE', 14, N'TCP/IP based  Standalone controller with User Capacity - 75,000 with Card reader module, Transaction - 2,50,000  ,  3.5'' TFT graphical Color Display LCD with Icons  , CapacitiveTouch Sense Keypad , POE (Power on Ethernet) Power Supply, Modular Reader Provision* (EM Proximity/Mifare/HID I Class/HID Prox) *(Not Included)    ,  Wiegand In & Wiegand Out Interface', 1, 2, 0, N'TCP,UDP', 1, 75000, 250000, N'', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (33, N'STNG30 - Wifi', 14, N'Wifi based  Standalone controller with User Capacity - 75,000 with Card reader module, Transaction - 2,50,000 , 3.5'' TFT graphical Color Display LCD with Icons   , CapacitiveTouch Sense Keypad ,  Standard 12 V Power Supply ,  Modular Reader Provision* (EM Proximity/Mifare/HID I Class/HID Prox) *(Not Included),   Wiegand In & Wiegand Out Interface', 1, 2, 0, N'', 1, 75000, 250000, N'', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (34, N'STNG30 - GPRS', 14, N'GPRS based  Standalone controller with User Capacity - 75,000 with Card reader module, Transaction - 2,50,000 3.5'' TFT graphical Color Display LCD with Icons CapacitiveTouch Sense Keypad,  Standard 12 V Power Supply Modular Reader Provision* (EM Proximity/Mifare/HID I Class/HID Prox) *(Not Included)  ,  Wiegand In & Wiegand Out Interface  GPRS Enabled SIM Card in Customer Scope', 1, 2, 0, N'TCP,UDP,GPRS', 1, 75000, 250000, N'', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (35, N'SBSN150 -P', 15, N'Fingerprint Reader with inbuilt Proximity Reader - Wiegand (26/32) o/p & RS485 / RS232 for template management. Finger Enrollment is either through BIOmini (SFU300) or BS-PR.', 1, 1, 1, N'Serial 485', 0, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (36, N'SBSN150 -S', 15, N'Fingerprint Reader with inbuilt Mifare Smart Card Reader - Wiegand (26/32) o/p & RS485 / RS232 for template management. Finger Enrollment is either through BIOmini (SFU300) or BS-PR.', 1, 1, 1, N'Serial 485', 0, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (37, N'SBSN150 - HI', 15, N'Fingerprint Reader with inbuilt HID Iclass Reader - Wiegand (26/32) o/p & RS485 / RS232 for template management. Finger Enrollment is either through BIOmini (SFU300) or BS-PR.', 1, 1, 1, N'Serial 485', 0, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (38, N'SBSN150 - HP', 15, N'Fingerprint Reader with inbuilt HID Prox Reader - Wiegand (26/32) o/p & RS485 / RS232 for template management. Finger Enrollment is either through BIOmini (SFU300) or BS-PR.', 1, 1, 1, N'Serial 485', 0, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (39, N'SBSN950 -P', 15, N'Fingerprint Reader with inbuilt Proximity Reader - Wiegand (26/32) o/p & RS485 / RS232 for template management. Finger Enrollment is either through BIOmini (SFU300) or BS-PR.', 1, 1, 1, N'Serial 485', 0, NULL, NULL, N'9500', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (40, N'SBSN950 -S', 15, N'Fingerprint Reader with inbuilt Mifare Smart Card Reader - Wiegand (26/32) o/p & RS485 / RS232 for template management. Finger Enrollment is either through BIOmini (SFU300) or BS-PR.', 1, 1, 1, N'Serial 485', 0, NULL, NULL, N'9500', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (41, N'SBSN950 - HI', 15, N'Fingerprint Reader with inbuilt HID Iclass Reader - Wiegand (26/32) o/p & RS485 / RS232 for template management. Finger Enrollment is either through BIOmini (SFU300) or BS-PR.', 1, 1, 1, N'Serial 485', 0, NULL, NULL, N'9500', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (42, N'SBSN950 - HP', 15, N'Fingerprint Reader with inbuilt HID Prox Reader - Wiegand (26/32) o/p & RS485 / RS232 for template management. Finger Enrollment is either through BIOmini (SFU300) or BS-PR.', 1, 1, 1, N'Serial 485', 0, NULL, NULL, N'9500', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (43, N'STNG30-P', 14, N' TCP/IP Based single door controller with Card Reader module (optional). Users - up to 75,000, Transactions - Up to 2,50,000. 3.5'' TFT graphical Color Display LCD , CapacitiveTouch Sense Keypad & Voice indication. Interface - TCP/IP, Wiegand (In&Out),Lock, magnetic contact,Buzzer,Exit switch, Fire Panel.  Standard 12 V Power Supply. Modular Reader Provision* (EM Proximity/Mifare/HID I Class/HID Prox) *(Reader Module Not Included). ', 1, 2, 0, N'TCP,UDP', 1, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (44, N'STNG30-S', 14, N'TCP/IP Based single door controller with Inbuilt Mifare Card Reader. Users - up to 75,000, Transactions - Up to 2,50,000. 3.5'' TFT graphical Color Display LCD , CapacitiveTouch Sense Keypad & Voice indication. Interface - TCP/IP, Wiegand (In&Out),Lock, magnetic contact,Buzzer,Exit switch, Fire Panel.  Standard 12 V Power Supply. Modular Reader Provision* (Mifare/HID I Class/HID Prox)', 1, 2, 0, N'TCP,UDP', 1, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (45, N'STNG30-HI', 14, N'TCP/IP Based single door controller with Inbuilt HID Iclass Card Reader. Users - up to 75,000, Transactions - Up to 2,50,000. 3.5'' TFT graphical Color Display LCD , CapacitiveTouch Sense Keypad & Voice indication. Interface - TCP/IP, Wiegand (In&Out),Lock, magnetic contact,Buzzer,Exit switch, Fire Panel.  Standard 12 V Power Supply. Modular Reader Provision* (EM Proximity/Mifare/HID Prox)', 1, 2, 0, N'TCP,UDP', 1, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (46, N'STNG30-HP', 14, N' TCP/IP Based single door controller with Inbuilt HID Prox Card Reader. Users - up to 75,000, Transactions - Up to 2,50,000. 3.5'' TFT graphical Color Display LCD , CapacitiveTouch Sense Keypad & Voice indication. Interface - TCP/IP, Wiegand (In&Out),Lock, magnetic contact,Buzzer,Exit switch, Fire Panel.  Standard 12 V Power Supply. Modular Reader Provision* (EM Proximity/Mifare/HID Prox)', 1, 2, 0, N'TCP,UDP', 1, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (47, N'SBNG930-P', 13, N' TCP/IP Based single door controller with one of the best Optical fingerprint sensor and with Inbuilt Proximity Card Reader.Template - Up to 9500 (1:N), Up to 3,00,000 (1:1) with Card Reader module, Transactions - Up to 2,50,000. 3.5'' TFT graphical Color Display LCD , CapacitiveTouch Sense Keypad & Voice indication,Standard 12 V Power Supply. Modular Reader Provision* (Mifare/HID I Class/HID Prox).', 1, 2, 0, N'TCP,UDP', 1, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (48, N'SBNG930-S', 13, N'TCP/IP Based single door controller with one of the best Optical fingerprint sensor and with Inbuilt Proximity Card Reader.Template - Up to 9500 (1:N), Up to 3,00,000 (1:1) with Card Reader module, Transactions - Up to 2,50,000. 3.5'' TFT graphical Color Display LCD , CapacitiveTouch Sense Keypad & Voice indication,Standard 12 V Power Supply. Modular Reader Provision* (Mifare/HID I Class/HID Prox).', 1, 2, 0, N'TCP,UDP', 1, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (49, N'SBNG930-HI', 13, N' TCP/IP Based single door controller with one of the best Optical fingerprint sensor and with Inbuilt HID Iclass Card Reader.Template - Up to 9500 (1:N), Up to 3,00,000 (1:1) with Card Reader module, Transactions - Up to 2,50,000. 3.5'' TFT graphical Color Display LCD , CapacitiveTouch Sense Keypad & Voice indication,Standard 12 V Power Supply. Modular Reader Provision* (Mifare/HID I Class/HID Prox)', 1, 2, 0, N'TCP,UDP', 1, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (50, N'SBNG930-HP', 13, N' TCP/IP Based single door controller with one of the best Optical fingerprint sensor and with Inbuilt HID Prox Card Reader.Template - Up to 9500 (1:N), Up to 3,00,000 (1:1) with Card Reader module, Transactions - Up to 2,50,000. 3.5'' TFT graphical Color Display LCD , CapacitiveTouch Sense Keypad & Voice indication,Standard 12 V Power Supply. Modular Reader Provision* (EM Proximity/Mifare/HID Prox)', 1, 2, 0, N'TCP,UDP', 1, NULL, NULL, N'1900', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (51, N'SMNG480', 3, N'', 4, 8, 0, N'TCP,UDP', 0, NULL, NULL, N'No', 0)
GO
INSERT [dbo].[ModelType] ([ModelTypeID], [ModelNo], [ModelMasterID], [ModelDescription], [NoOfDoors], [NoOfReaders], [IsBiometric], [CommunicationSupportType], [IsPinProx], [NoOfUsers], [NoOfTranx], [Template], [MarkDeleted]) VALUES (52, N'SMNG440', 2, N'', 4, 4, 0, N'TCP,UDP', 0, NULL, NULL, N'No', 0)
GO
SET IDENTITY_INSERT [dbo].[ModelType] OFF
GO
